download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/vmware-vmware-2.0.1.tar.gz
format_version: 1.0.0
name: vmware
namespace: vmware
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/vmware/vmware/versions/2.0.1/
