---
- name: Create VM using vCenter role
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - /root/create_vm_role/vars/main.yml
  tasks:
    - name: Install requests module at runtime
      ansible.builtin.command: pip3 install requests
      changed_when: false  # prevents showing this as "changed" in output
      ignore_errors: true   # in case it's already installed or fails silently

  roles:
    - create_vm_role

